# Generated by Django 4.1.10 on 2024-05-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifs', '0003_tarifs_client_id_tarifs_nature_bien'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifs',
            name='ref_client',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
