# Generated by Django 4.1.10 on 2024-05-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifs', '0004_tarifs_ref_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifs',
            name='nature_bien_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
